src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    //#[Assert\Unique]
    private $nom_prenom;

    #[ORM\Column(type: 'string', length: 1, nullable: true)]
    #[Assert\Choice(['M', 'F'])]
    private $sexe;

    #[ORM\Column(type: 'datetime')]
    //#[Assert\DateTime]
    private $date_de_naissance;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Country]
    private $nationalite;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'auteurs')]
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(?string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function __toString(): string{
        return $this->nom_prenom;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Isbn(
        type: Assert\Isbn::ISBN_13,
        message: 'This value is not valid ISBN13.',
    )]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'integer')]
    #[Assert\Positive]
    private $nombre_pages;

    #[ORM\Column(type: 'datetime')]
    private $date_de_parution;

    #[ORM\Column(type: 'integer', nullable: true)]
    #[Assert\Range(
        min: 0,
        max: 20,
        notInRangeMessage: 'Note doit être entre {{ min }} et {{ max }}.',
    )]
    private $note;

    #[ORM\ManyToMany(targetEntity: Auteur::class, mappedBy: 'livres')]
    private $auteurs;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $genres;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function __toString(): string{
        return $this->titre;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;


class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn')
            ->add('titre')
            ->add('nombre_pages')
            ->add('date_de_parution',DateTimeType::class,['widget'=>'single_text'])
            ->add('note')
            ->add('description')
            ->add('auteurs')
            ->add('genres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\AuteurRepository;
use App\Repository\GenreRepository;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class LivreController extends AbstractController
{

    #[Route('/', name: 'livre_home', methods: ['GET', 'POST'])]
    public function home(Request $request, LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository): Response
    {
        $livres = $livreRepository->findAll();
        if($request->isMethod('POST')){
            $livres = $this->handelFilters($request, $livreRepository, $genreRepository, $auteurRepository);
        }

        return $this->render('livre/home.html.twig', [
            'livres' => $livres,
            'auteurs' => $auteurRepository->findAll(),
            'genres' => $genreRepository->findAll(),
        ]);
    }

    private function handelFilters(Request $request, LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository){

        if($request->get('keywords')){
            return $livreRepository->findByTitreField($request->get('keywords'));
        }
        else if($request->get('note')){
            return $livreRepository->findByNoteField($request->get('note'));
        }
        else if($request->get('date1') && $request->get('date2') ){
            return $livreRepository->findByDateField($request->get('date1'), $request->get('date2'));
        }
        else if($request->get('author')){
            $id = $request->get("author");
            $author = $auteurRepository->find($id);
            return $author->getLivres();
        }
        else if($request->get('category')){
            $id = $request->get("category");
            $genre = $genreRepository->find($id);
            return $genre->getLivres();
        }
        else{
            return $livreRepository->findAll();
        }

    }
/*
    private function redirectAnonymousUsersToLogin(Request $request){
        //$this->get('security.context')
        if(!$request->get('security.context')->isGranted('ROLE_ADMIN') && !$request->get('security.context')->isGranted('ROLE_ADMIN') ){
            return new RedirectResponse($this->urlGenerator->genetare('app_login'));
        }
    }
*/
    #[Route('/livre', name: 'livre_index', methods: ['GET'])]
    public function index(Request $request, LivreRepository $livreRepository): Response
    {

        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    #[Route('/livre/new', name: 'livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/livre/{id}', name: 'livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/livre/{id}/edit', name: 'livre_edit', methods: ['GET', 'POST'])]
    #[ParamConverter('id', class: 'Livre', options:['id'=>'id'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/livre/{id}/delete', name: 'livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    {# class="btn btn-primary mt-3 mb-3"> <i class="fas fa-arrow-alt-circle-left"></i> #}
    <button class="btn btn-block btn-danger mb-4 btn-sm"><i class="fas fa-trash"></i> Delete</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-dark btn-block btn-sm"><i class="fas fa-save"></i> {{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-8 offset-2 login p-4 mt-5 mb-5">
            <h1 class="mt-3 mb-4">Edit Livre</h1>

            {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

            {# class="btn btn-primary mt-3 mb-3" <i class="fas fa-arrow-alt-circle-left"></i> #}
            <a href="{{ path('livre_index') }}" class="btn btn-primary mt-3 mb-3 btn-sm"> <i class="fas fa-arrow-alt-circle-left"></i> back to list</a>

            {{ include('livre/_delete_form.html.twig') }}
        </div>
    </div>


{% endblock %}

templates/livre/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Home
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/home.css') }}" />
{% endblock %}

{% block body %}



  <div class="">
      <div class="row text-center text-capitalize welcome-header">
          <h1>Welcome to BookStore</h1>
          <p class="lead">{{ livres | length }} books available</p>
          {% if not app.user %}
              <div class="alert alert-info" role="alert">
                  <a href="{{ path('app_login') }}">Login</a>, or <a href="{{ path('app_register') }}">create an account</a> to have more options.
              </div>
          {% endif %}
      </div>
      <div class="row main">
          <div class="col-4 filters">
              <h2 class="mt-2">Filters</h2>
              <p>Search with a key word</p>
              <form class="d-flex mt-4" method="post">
                  <div class="input-group mb-3">
                      <input name="keywords" type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">
                      <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                          <i class="fas fa-search"></i>
                      </button>
                  </div>
              </form>
              <hr>
              <p>Get the books published between two dates</p>
              <form class="d-flex mt-4" method="post">
                  <div class="input-group mb-3">
                      <input  name="date1" type="date" class="form-control" placeholder="Date from" aria-label="Date from">
                      <input  name="date2" type="date" class="form-control" placeholder="Date to" aria-label="Date to" aria-describedby="button-addon2">
                      <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                          <i class="fas fa-filter"></i>
                      </button>
                  </div>
              </form>
              <hr>
              <p>Get the books of an author</p>
                  <form class="d-flex mt-4" method="post">
                      <div class="input-group">
                          <select name="author" class="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
                              {% for auth in auteurs %}
                                  <option value="{{ auth.id }}">{{ auth.nomPrenom }}</option>
                              {% endfor %}
                          </select>
                          <button class="btn btn-outline-secondary" type="submit">
                              <i class="fas fa-filter"></i>
                          </button>
                      </div>
                  </form>
              <hr>
              <p>Get the books that belongs to a category</p>

              <form class="d-flex mt-4" method="post">
                  <div class="input-group">
                      <select name="category" class="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
                          {% for cate in genres %}
                              <option value="{{ cate.id }}">{{ cate.nom }}</option>
                          {% endfor %}
                      </select>
                      <button class="btn btn-outline-secondary" type="submit">
                          <i class="fas fa-filter"></i>
                      </button>
                  </div>
              </form>
              <hr>

              <p>Get the books by their rating</p>
              <form class="d-flex mt-4" method="post">
                  <div class="input-group">
                      <select name="note" class="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
                          {% for i in 0..20 %}
                              <option value="{{ i }}">{{ i }} / 20</option>
                          {% endfor %}
                      </select>
                      <button class="btn btn-outline-secondary" type="submit">
                          <i class="fas fa-filter"></i>
                      </button>
                  </div>
              </form>

          </div>
          <div class="col-8">
              <section class="books">
                  <div class="container">
                      <div class="">
                          {% for livre in livres %}
                              <div class="row book mb-3">
                                  <div class="col-3">
                                      <img src="..."
                                           srcset="https://covers.openlibrary.org/b/isbn/{{ livre.isbn }}-M.jpg ,
                                            https://via.placeholder.com/150/150"
                                           class="" alt="Could not load cover"
                                           style="width: 120px; height:auto;"
                                      >
                                  </div>
                                  <div class="col-9">
                                      <h4>{{ livre.titre }} <span class="badge rounded-pill bg-warning text-dark">
                                                  {{ livre.note ? livre.note : '_' }}/20
                                              </span>
                                      </h4>
                                      By:
                                      {% for auteur in livre.auteurs %}
                                        <span> {{ auteur }}</span>,
                                      {% endfor %}
                                      <p>{{ livre.dateDeParution | date('Y-m-d') }}<span class="nombre-pages">{{ livre.nombrePages }} pages </span></p>


                                      <div class="row">
                                          <div class="col-9">
                                              {% for category in livre.genres %}
                                                  <span class="badge rounded-pill bg-secondary">
                                                {{ category ? category : 'genre non definie' }}
                                              </span>
                                              {% endfor %}
                                          </div>
                                          <div class="col-3">
                                              <a href="{{ path('livre_show', {'id': livre.id}) }}" class="btn btn-outline-dark btn-sm w-100">Show more</a>
                                          </div>
                                      </div>


                                  </div>
                              </div>

                          {% endfor %}
                      </div>
                  </div>
              </section>
          </div>
      </div>
  </div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}

{% block body %}
    <h1>Livre index</h1>
    {# class="btn btn-primary mt-3 mb-3"> <i class="fas fa-arrow-alt-circle-left"></i> #}
    {#% if app.user and 'ROLE_ADMIN' in app.user.roles %#}
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('livre_new') }}" class="btn btn-primary mt-3 mb-3 btn-sm"> <i class="fas fa-plus-circle"></i> Create new</a>
    {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Isbn</th>
                <th>Titre</th>
                <th>Nombre_pages</th>
                <th>Date_de_parution</th>
                <th>Note</th>
                {# <th>Description</th>  #}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td>{{ livre.isbn }}</td>
                <td>{{ livre.titre }}</td>
                <td>{{ livre.nombrePages }}</td>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ livre.note }}</td>
                {#
                <td>{{ livre.description }}</td>
                #}
                <td>
                    <a href="{{ path('livre_show', {'id': livre.id}) }}" class="btn btn-dark text-light btn-sm"> <i class="fas fa-eye"></i></a>
                    {#% if app.user and 'ROLE_ADMIN' in app.user.roles %#}
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('livre_edit', {'id': livre.id}) }} " class="btn btn-secondary btn-sm"><i class="fas fa-edit"></i></a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-8 offset-2 mt-5 mb-5 p-4 login">
            <h1 class="mb-3">Create new Livre</h1>

            {{ include('livre/_form.html.twig') }}

            <a href="{{ path('livre_index') }}" class="btn btn-primary mt-3 mb-3 btn-sm">
                <i class="fas fa-arrow-alt-circle-left"></i> back to list
            </a>
        </div>
    </div>

{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <h1 class="mt-4 mb-5">{{ livre.titre }}</h1>



    <div class="row">
        <div class="col-md-5">
            <img src="..."
                 srcset="https://covers.openlibrary.org/b/isbn/{{ livre.isbn }}-L.jpg ,
                                        https://via.placeholder.com/150/150"
                 class="" alt="cover"

            >
        </div>
        <div class="col-md-7">
            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ livre.id }}</td>
                </tr>
                <tr>
                    <th>Isbn</th>
                    <td>{{ livre.isbn }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ livre.titre }}</td>
                </tr>
                <tr>
                    <th>Nombre_pages</th>
                    <td>{{ livre.nombrePages }}</td>
                </tr>
                <tr>
                    <th>Date_de_parution</th>
                    <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Note</th>
                    <td>{{ livre.note }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ livre.description }}</td>
                </tr>
                <tr>
                    <th>Auteurs</th>
                    <td>
                        {% for auteur in livre.auteurs %}
                           <a href="{{ path('auteur_show', {'id':auteur.id}) }}" class="badge bg-secondary">{{ auteur.nomPrenom }}</a>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Genres</th>
                    <td>
                        {% for genre in livre.genres %}
                            <a href="{{ path('genre_show', {'id':genre.id}) }}" class="badge rounded-pill bg-info text-dark">{{ genre.nom }}</a>
                        {% endfor %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <a href="{{ path('livre_index') }}" class="btn btn-primary mt-3 mb-3 btn-sm"> <i class="fas fa-arrow-alt-circle-left"></i> back to list</a>

    {#% if app.user and 'ROLE_ADMIN' in app.user.roles %#}
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('livre_edit', {'id': livre.id}) }}" class="btn btn-secondary mt-3 mb-3 btn-sm"> <i class="fas fa-edit"></i> edit</a>

    {{ include('livre/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}